name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Linter
        run: npm run test

      - name: Formatter
        run: npm run prettier

      - name: Test
        env:
          CI: true
        run: npm run test

      - name: Build
        run: npm run build
